name: install-graphviz
description: 'Install Graphviz cross-platform (Linux, macOS, Windows)'
branding: 
  icon: 'download'
  color: 'gray-dark'

runs:
  using: "composite"
  steps:
    - name: Install Dependencies (Linux)
      if: runner.os == 'Linux'
      run: sudo apt-get install graphviz
      shell: bash
    - name: Install Dependencies (Windows)
      if:  == 'Windows'
      run: choco install graphviz
      shell: bash
    - name: Install Dependencies (macOS)
      if:  == 'macOS'
      run: brew install graphviz
      shell: bash